openapi: 3.1.0
info:
  title: API PDV - Equipe Ansiedade Code
  version: 1.0.0
  description: >-
    API desenvolvida como projeto final do curso DDS Backend T16 da Cubos
    Academy
servers:
  - url: http://localhost:3000
    description: API de Teste
  - url: https://desafio-backend-final-dds-t16-gjyx.onrender.com
    description: Deploy Produção
tags:
  - name: Login
  - name: Usuários
    description: Todos os endpoints de usuários.
  - name: Clientes
    description: Todos os endpoints de clientes.
  - name: Produtos
    description: Todos os endpoints de produtos.
  - name: Pedidos
    description: Todos os endpoints de pedidos.
  - name: Categorias
paths:
  /login:
    post:
      tags:
        - Login
      summary: Endpoint para realizar login do usuário.
      responses:
        '200':
          description: Login realizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request        
        '401':
          description: Falha na autenticação
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      mensagem:
                        type: string
                  - type: object
                    properties:
                      mensagem:
                        type: string
                  - type: object
                    properties:
                      mensagem:
                        type: string
                  - type: object
                    properties:
                      mensagem:
                        type: string      
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Erro de credenciais
                  value:
                    mensagem: Usuário e/ou senha inválido(s).      
                Exemplo4:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '500':
          description: Erro interno do servidor.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              ExemploLogin:
                summary: Exemplo de login
                value:
                  email: messiasdosanjos8709@exemplo.com
                  senha: '123456'
  /usuario:
    post:
      tags:
        - Usuários
      summary: Endpoint para cadastrar usuário.
      description: ''
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioResponse'
        '400':
          description: Bad Request
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Email já cadastrado
                  value:
                    mensagem: Já existe usuário cadastrado com o e-mail informado.          
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRequest'
            examples:
              ExemploCadastro:
                summary: Exemplo Completo Cadastro
                value:
                  nome: Messias Santos
                  email: messiasdosanjos8709@exemplo.com
                  senha: '123456'
    get:
      tags:
        - Usuários
      summary: Endpoint para detalhar usuário logado.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioResponse'
        '401':
          description: 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
    put:
      tags:
        - Usuários
      summary: Endpoint para alterar dados do usuário.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Atualização com sucesso.
                  value:
                    mensagem: Usuário atualizado com sucesso.
        '400':
          description: Bad Request
        '401':
          description: 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Email já sendo utilizado
                  value:
                    mensagem: O e-mail informado já está sendo utilizado por outro usuário.
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioUpdate'
            examples:
              ExemploAtualizar:
                summary: Exemplo Completo Atualização
                value:
                  nome: Messias Santos
                  email: messiasdosanjos8709@exemplo.com
  /categoria:
    get:
      tags:
        - Categorias
      summary: Endpoint para listar todas as categorias.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    descricao:
                      type: string  
        '500':
          description: Internal Server Error
  /usuario/redefinir:
    patch:
      tags:
        - Usuários
      summary: Endpoint para redefinir senha do usuário.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Atualização com sucesso.
                  value:
                    mensagem: Senha atualizada com sucesso.
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedefinirSenha'
            examples:
              ExemploRedefinirSenha:
                summary: Redefinir Senha
                value:
                  email: messiasdosanjos8709@exemplo.com
                  senha_antiga: 123456
                  senha_nova: 1234
  /cliente:
    post:
      tags:
        - Clientes
      summary: Endpoint para cadastrar cliente.
      description: ''
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictClientes'
              examples:
                Exemplo1:
                  summary: Email já utilizado
                  value:
                    mensagem: Já existe cliente cadastrado com o e-mail informado.
                Exemplo2:
                  summary: CPF já utilizado
                  value:
                    mensagem: Já existe cliente cadastrado com o CPF informado.
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
    get:
      tags:
        - Clientes
      summary: Endpoint para listar todos os clientes.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
  /cliente/{id}:
    get:
      tags:
        - Clientes
      summary: Endpoint para detalhar cliente especificado.
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Id do cliente
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Cliente não encontrado.
                  value:
                    mensagem: Cliente não encontrado.
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
    put:
      tags:
        - Clientes
      summary: Endpoint para alterar dados de cliente especificado.
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Id do cliente
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Sucesso
                  value:
                    mensagem: Os dados do cliente foram alterados com sucesso.
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Cliente não encontrado.
                  value:
                    mensagem: Cliente não encontrado.
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictClientes'
              examples:
                Exemplo1:
                  summary: Email já utilizado
                  value:
                    mensagem: Já existe cliente cadastrado com o e-mail informado.
                Exemplo2:
                  summary: CPF já utilizado
                  value:
                    mensagem: Já existe cliente cadastrado com o CPF informado.
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
  /produto:
    post:
      tags:
        - Produtos
      summary: Endpoint para cadastrar produto.
      description: ''
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoResponse'
        '400':
          description: Bad Request
        '401':
          description: 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Produto não encontrado.
                  value:
                    mensagem: Produto não encontrado.              
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
            examples:
              ExemploCadastro:
                summary: Exemplo Cadastro Completo
                value:
                  descricao: EA Sports FC 24 - PlayStation 5
                  quantidade_estoque: 12
                  valor: 15460
                  categoria_id: 9
              ExemploCadastroErroCategoria:
                summary: Exemplo Cadastro Erro Categoria
                value:
                  descricao: EA Sports FC 24 - Xbox Series X
                  quantidade_estoque: 19
                  valor: 15460
                  categoria_id: 990
              ExemploComErroCampoObrigatorio:
                summary: Exemplo Cadastro Erro Campo Obrig.
                value:
                  descricao: EA Sports FC 24 - Xbox Series X
                  quantidade_estoque: 19
                  categoria_id: 9
    get:
      tags:
        - Produtos
      summary: Endpoint para listar todos os produtos.
      description: ''
      parameters:
        - name: categoria_id
          in: query
          schema:
            type: integer
          description: Id da categoria.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProdutoResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Categoria não encontrada.
                  value:
                    mensagem: Categoria informada não encontrada.              
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
  /produto/{id}:
    get:
      tags:
        - Produtos
      summary: Endpoint para detalhar produto especificado.
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Id do produto
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ProdutoResponse'
                  - type: object
                    properties:
                      imagem_url:
                        type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Produto não encontrado.
                  value:
                    mensagem: Produto não encontrado.
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
    put:
      tags:
        - Produtos
      summary: Endpoint para alterar dados de produto especificado.
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Id do produto
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Atualização com sucesso.
                  value:
                    mensagem: Produto atualizado com sucesso.
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Produto não encontrado.
                  value:
                    mensagem: Produto não encontrado.
                Exemplo2:
                  summary: Categoria não encontrada.
                  value:
                    mensagem: Categoria informada não encontrada.    
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
            examples:
              ExemploUpdate:
                summary: Exemplo Update Completo
                value:
                  descricao: EA Sports FC 24 - PlayStation 5
                  quantidade_estoque: 10
                  valor: 15460
                  categoria_id: 9
              ExemploUpdateErroCategoria:
                summary: Exemplo Update Erro Categoria
                value:
                  descricao: EA Sports FC 24 - Xbox Series X
                  quantidade_estoque: 10
                  valor: 15460
                  categoria_id: 990
              ExemploComErroCampoObrigatorio:
                summary: Exemplo Update Erro Campo Obrig.
                value:
                  descricao: EA Sports FC 24 - Xbox Series X
                  quantidade_estoque: 10
                  categoria_id: 9
    delete:
      tags:
        - Produtos
      summary: Endpoint para excluir produto.
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Id do produto
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Exclusão com sucesso.
                  value:
                    mensagem: Produto excluído com sucesso.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Existe pedidopara o produto.
                  value:
                    mensagem: >-
                      Não é possível excluir o produto, pois ele está 
                      vinculado a um ou mais pedidos.      
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Produto não encontrado.
                  value:
                    mensagem: Produto não encontrado.    
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
  /produto/{id}/imagem:
    patch:
      tags:
        - Produtos
      summary: Endpoint para cadastrar imagem para produto especificado.
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Requisição e produto sem imagem
                  value:
                    mensagem: Imagem do produto já atualizada.
                    imagem_url: null
                Exemplo2:
                  summary: Requisição sem imagem e produto com imagem
                  value:
                    mensagem: Imagem removida com sucesso.
                    imagem_url: null   
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Atualização com sucesso
                  value:
                    mensagem: Imagem atualizada com sucesso.
                    imagem_url: url
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Imagem não fornecida
                  value:
                    mensagem: A propriedade imagem deve ser fornecida na requisição.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Produto não encontrado.
                  value:
                    mensagem: Produto não encontrado.
        '500':
          description: Internal Server Error
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                imagem:
                  type: string
                  format: binary
                  description: >-
                    Selecione um arquivo de imagem. Ex.: (.jpg, .jpeg, .png,
                    .gif)
      security:
        - bearerAuth: []
  /pedido:
    post:
      tags:
        - Pedidos
      summary: Endpoint para cadastrar pedidos.
      description: ''
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PedidoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Estoque insuficiente.
                  value:
                    mensagem: >-
                      Pedido não realizado. Produto id 0 não possui
                      estoque suficiente para o pedido.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Cliente não encontrado.
                  value:
                    mensagem: Cliente não encontrado.
                Exemplo2:
                  summary: Produto não encontrado.
                  value:
                    mensagem: Pedido não realizado. Produto id 0 não encontrado.               
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PedidoRequest'
            examples:
              ExemploPedido:
                summary: Exemplo de Pedido
                value:
                  cliente_id: 2
                  observacao: "Pode entregar no vizinho do 202"
                  pedido_produtos:
                    - produto_id: 3
                      quantidade_produto: 3
                    - produto_id: 5
                      quantidade_produto: 1
      security:
        - bearerAuth: []
    get:
      tags:
        - Pedidos
      summary: Endpoint para listar pedidos.
      description: ''
      parameters:
        - name: cliente_id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    pedido:
                      type: object
                      properties:
                        id:
                          type: integer
                        valor_total:
                          type: integer
                        observacao:
                          type: string
                        cliente_id:
                          type: integer
                    pedido_produtos:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          quantidade_produto:
                            type: integer
                          valor_produto:
                            type: integer
                          pedido_id:
                            type: integer
                          produto_id:
                            type: integer
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
              examples:
                Exemplo1:
                  summary: Token não enviado
                  value:
                    mensagem: >-
                      Para acessar este recurso um token de autenticação
                      válido deve ser enviado.
                Exemplo2:
                  summary: Usuário token sem acesso
                  value:
                    mensagem: Acesso não autorizado.
                Exemplo3:
                  summary: Autenticação falhou
                  value:
                    mensagem: >-
                      Autenticação falhou. Por favor, verifique as
                      credenciais e tente novamente!
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
              examples:
                Exemplo1:
                  summary: Cliente não encontrado.
                  value:
                    mensagem: Cliente não encontrado.              
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        senha:
          type: string
      required:
        - email
        - senha
    LoginResponse:
      type: object
      properties:
        usuario:
          $ref: '#/components/schemas/UsuarioResponse'
        token:
          type: string
    UsuarioResponse:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
          format: email
    UsuarioRequest:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
          format: email
        senha:
          type: string
      required:
        - nome
        - email
        - senha   
    UsuarioUpdate:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
          format: email
      required:
        - nome
        - email
    RedefinirSenha:
      type: object
      properties:
        email:
          type: string
          format: email
        senha_antiga:
          type: string
        senha_nova:
          type: string  
      required:
        - email
        - senha_antiga
        - senha_nova
    ClienteResponse:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
          format: email
        cpf:
          type: string
        cep:
          type: string
        rua:
          type: string
        numero:
          type: string
        bairro:
          type: string
        cidade:
          type: string
        estado:
          type: string                                      
    Produto:
      type: object
      properties:
        descricao:
          type: string
        quantidade_estoque:
          type: integer
        valor:
          type: integer
        categoria_id:
          type: integer
      required:
        - descricao
        - quantidade_estoque
        - valor
        - categoria_id
    ProdutoResponse:
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
        quantidade_estoque:
          type: integer
        valor:
          type: integer
        categoria_id:
          type: integer      
    Cliente:
      type: object
      properties:
        nome:
          type: string
          example: Malaquias de Jesus Santos
        email:
          type: string
          example: obinakiller@gmail.com
        cpf:
          type: string
          example: 136.015.055-25
        cep:
          type: 87876-898
        rua:
          type: Rua dos Andrades
        numero:
          type: 987A
        bairro:
          type: Santo Antônio
        cidade:
          type: Porto Seguro
        estado:
          type: Bahia
      required:
        - nome
        - email
        - cpf
    PedidoResponse:
      type: object
      properties:
        cliente_id:
          type: integer
        observacao:
          type: string
        pedido_produtos:
          type: array
          items:
            type: object
            properties:
              produto_id:
                type: integer
              quantidade_produto:
                type: integer
            required:
              - produto_id
              - quantidade_produto
      required:
        - cliente_id
        - pedido_produtos
    PedidoRequest:
      type: object
      properties:
        cliente_id:
          type: integer
        observacao:
          type: string
        pedido_produtos:
          type: array
          items:
            type: object
            properties:
              produto_id:
                type: integer
              quantidade_produto:
                type: integer
            required:
              - produto_id
              - quantidade_produto
      required:
        - cliente_id
        - pedido_produtos    
    UnauthorizedResponse:
      oneOf:
        - type: object
          properties:
            mensagem:
              type: string
        - type: object
          properties:
            mensagem:
              type: string
        - type: object
          properties:
            mensagem:
              type: string    
    ConflictClientes:
      oneOf:
        - type: object
          properties:
            mensagem:
              type: string
        - type: object
          properties:
            mensagem:
              type: string          
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT